### ISSUE TITLE
A typo in the ban.js file

### ISSUE THREAD

**Issue by spacesanjeet** [Dob6458/DoBot-Discord#1]
I have found a bug in the code, in a file named ban.js in the commands folder.
`if (!message.member.hasPermission("BAN_MEMBERS")) {
    return message.channel.send(":warning: You have not a 'BAn_MEMBERS' permission").then((msg) => {
      msg.delete(6000)
    });
  }`

I think it should be:
`if (!message.member.hasPermission("BAN_MEMBERS")) {
    return message.channel.send(":warning: You have not a 'BAN_MEMBERS' permission").then((msg) => {
      msg.delete(6000)
    });
  }`

**Comment by Dob6458** [comment]
Thanks, I will correct it if I have my time 😉

**Comment by spacesanjeet** [comment]
> Thanks, I will correct it if I have my time 😉

Okie. And thanks for the consideration.

**Comment by Dob6458** [comment]
@spacesanjeet I've fixed code in `ban.js`.
